"""del driver_id  at  deliveries table

Revision ID: 12ff8ccef661
Revises: cd3de0201d89
Create Date: 2026-08-21 13:51:57.501452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ff8ccef661'
down_revision: Union[str, Sequence[str], None] = 'cd3de0201d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_driver_id'), table_name='deliveries')
    op.drop_constraint(op.f('deliveries_driver_id_fkey'), 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('deliveries_driver_id_fkey'), 'deliveries', 'drivers', ['driver_id'], ['id'])
    op.create_index(op.f('ix_deliveries_driver_id'), 'deliveries', ['driver_id'], unique=False)
    # ### end Alembic commands ###
