"""relationships orders-sellers revision

Revision ID: 19b202f2f978
Revises: 34e43a0e2e11
Create Date: 2026-07-27 11:23:15.139202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b202f2f978'
down_revision: Union[str, Sequence[str], None] = '34e43a0e2e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('supervisor_id', sa.Uuid(), nullable=False))
    op.add_column('orders', sa.Column('manager_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_orders_manager_id'), 'orders', ['manager_id'], unique=False)
    op.create_index(op.f('ix_orders_supervisor_id'), 'orders', ['supervisor_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'salesperson', ['supervisor_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'salesperson', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_supervisor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_manager_id'), table_name='orders')
    op.drop_column('orders', 'manager_id')
    op.drop_column('orders', 'supervisor_id')
    # ### end Alembic commands ###
