"""add unit_weight in product table

Revision ID: 350bd12344de
Revises: e2cef468bf2d
Create Date: 2026-08-13 20:08:00.954518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350bd12344de'
down_revision: Union[str, Sequence[str], None] = 'e2cef468bf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit_weight')
    # ### end Alembic commands ###
