"""update db and relationships

Revision ID: 3a8a46fd8a62
Revises: 4b11aefd8862
Create Date: 2026-07-27 10:48:13.556664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "3a8a46fd8a62"
down_revision: Union[str, Sequence[str], None] = "4b11aefd8862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sa.String(length=50), server_default="B", nullable=False),
        sa.Column("validity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ear", sa.Boolean(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesperson",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trade_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "profile", sa.String(length=50), server_default="seller", nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_salesperson_code"), "salesperson", ["code"], unique=True)
    op.create_table(
        "deliveries",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("car_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("confirmed_by_driver", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_car_id"), "deliveries", ["car_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_driver_id"), "deliveries", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_order_id"), "deliveries", ["order_id"], unique=True
    )
    op.drop_table("driver_profiles")
    op.drop_constraint(op.f("cars_driver_id_fkey"), "cars", type_="foreignkey")
    op.create_foreign_key(None, "cars", "drivers", ["driver_id"], ["id"])
    op.add_column("orders", sa.Column("saller_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_orders_saller_id"), "orders", ["saller_id"], unique=False)
    op.create_foreign_key(None, "orders", "salesperson", ["saller_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_saller_id"), table_name="orders")
    op.drop_column("orders", "saller_id")
    op.drop_constraint(None, "cars", type_="foreignkey")
    op.create_foreign_key(
        op.f("cars_driver_id_fkey"), "cars", "users", ["driver_id"], ["id"]
    )
    op.create_table(
        "driver_profiles",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("license", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'B'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "validity",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ear", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("driver_profiles_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("driver_profiles_pkey")),
    )
    op.drop_index(op.f("ix_deliveries_order_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_driver_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_car_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_salesperson_code"), table_name="salesperson")
    op.drop_table("salesperson")
    op.drop_table("drivers")
    # ### end Alembic commands ###
