"""alter fields at deliveries table

Revision ID: 4510705090fd
Revises: ce1524dbff2f
Create Date: 2026-08-21 11:36:08.486222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4510705090fd"
down_revision: Union[str, Sequence[str], None] = "ce1524dbff2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliveries", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column(
        "deliveries",
        sa.Column("invoice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "deliveries",
        sa.Column("delivery_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "deliveries", sa.Column("delivery_confirmed", sa.Boolean(), nullable=False)
    )
    op.drop_index(op.f("ix_deliveries_cargo_weight"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_invoice_number"), table_name="deliveries")
    op.drop_column("deliveries", "confirmed_by_driver")
    op.drop_column("deliveries", "invoice_number")
    op.drop_column("deliveries", "updated_at")
    op.drop_column("deliveries", "confirmed_at")
    op.drop_column("deliveries", "cargo_weight")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deliveries",
        sa.Column("cargo_weight", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deliveries",
        sa.Column(
            "confirmed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deliveries",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deliveries",
        sa.Column("invoice_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deliveries",
        sa.Column(
            "confirmed_by_driver", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.create_index(
        op.f("ix_deliveries_invoice_number"),
        "deliveries",
        ["invoice_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deliveries_cargo_weight"), "deliveries", ["cargo_weight"], unique=False
    )
    op.drop_column("deliveries", "delivery_confirmed")
    op.drop_column("deliveries", "delivery_at")
    op.drop_column("deliveries", "invoice")
    op.drop_column("deliveries", "weight")
    # ### end Alembic commands ###
