"""alter contact column client table

Revision ID: 4b11aefd8862
Revises: cb27ed37420c
Create Date: 2026-07-19 12:11:23.860707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4b11aefd8862"
down_revision: Union[str, Sequence[str], None] = "cb27ed37420c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("clients", "contact", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("clients", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.alter_column("clients", "contact", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("clients", "zip_code")
    op.drop_column("clients", "phone")
    # ### end Alembic commands ###
