"""add and alter date columns in delivery table

Revision ID: 5ce446cbb0ee
Revises: 6fc24ee48f7b
Create Date: 2026-09-03 11:06:47.882245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce446cbb0ee'
down_revision: Union[str, Sequence[str], None] = '6fc24ee48f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('delivered_confirmed', sa.Boolean(), nullable=False))
    op.drop_column('deliveries', 'delivery_confirmed')
    op.drop_column('deliveries', 'delivery_at')
    op.alter_column('stock_movements', 'movement_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'movement_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('deliveries', sa.Column('delivery_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('delivery_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('deliveries', 'delivered_confirmed')
    op.drop_column('deliveries', 'delivered_at')
    op.drop_column('deliveries', 'scheduled_at')
    # ### end Alembic commands ###
