"""alter inventory table

Revision ID: 6abf8ba19932
Revises: dfe5cd0df175
Create Date: 2026-08-19 15:54:42.317306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "6abf8ba19932"
down_revision: Union[str, Sequence[str], None] = "dfe5cd0df175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "updated_at")
    op.add_column(
        "stock_movements",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_stock_movements_code"), "stock_movements", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_order_id"),
        "stock_movements",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_order_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_code"), table_name="stock_movements")
    op.drop_column("stock_movements", "code")
    op.add_column(
        "products",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
