"""add observations field at deliveries table

Revision ID: 7dc53a99367f
Revises: 12ff8ccef661
Create Date: 2026-08-21 13:57:04.736284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7dc53a99367f"
down_revision: Union[str, Sequence[str], None] = "12ff8ccef661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deliveries",
        sa.Column("observations", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliveries", "observations")
    # ### end Alembic commands ###
