"""add drivers_profile table

Revision ID: 8d486df9f056
Revises: f07555f99774
Create Date: 2026-06-26 16:00:41.686914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "8d486df9f056"
down_revision: Union[str, Sequence[str], None] = "f07555f99774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Criar a nova tabela
    op.create_table(
        "driver_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sa.String(length=50), server_default="B", nullable=False),
        sa.Column("validity", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id"),
    )

    # 2. Remover FK e index ANTES de dropar drivers
    op.drop_constraint("cars_driver_id_fkey", "cars", type_="foreignkey")
    op.drop_index(op.f("ix_cars_driver_id"), table_name="cars")

    # 3. Agora é seguro dropar drivers
    op.drop_table("drivers")

    # 4. Recriar index com unique=True (garante 1:1) e nova FK -> users
    op.create_index(op.f("ix_cars_driver_id"), "cars", ["driver_id"], unique=True)
    op.create_foreign_key("cars_driver_id_fkey", "cars", "users", ["driver_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cars", type_="foreignkey")
    op.create_foreign_key(
        op.f("cars_driver_id_fkey"), "cars", "drivers", ["driver_id"], ["id"]
    )
    op.drop_index(op.f("ix_cars_driver_id"), table_name="cars")
    op.create_index(op.f("ix_cars_driver_id"), "cars", ["driver_id"], unique=False)
    op.create_table(
        "drivers",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cpf", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("license", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'B'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "validity", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("drivers_pkey")),
    )
    op.drop_table("driver_profiles")
    # ### end Alembic commands ###
