"""new database structure

Revision ID: 98630ddc391a
Revises: be931ceb117a
Create Date: 2026-08-03 10:55:13.901976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "98630ddc391a"
down_revision: Union[str, Sequence[str], None] = "be931ceb117a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trade_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("insc_e", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "code", name="uq_stores_client_code"),
    )
    op.create_index(op.f("ix_stores_client_id"), "stores", ["client_id"], unique=False)
    op.create_index(op.f("ix_stores_code"), "stores", ["code"], unique=False)
    op.drop_index(op.f("ix_clients_cnpj"), table_name="clients")
    op.drop_index(op.f("ix_clients_insc_e"), table_name="clients")
    op.drop_column("clients", "created_at")
    op.drop_column("clients", "contact")
    op.drop_column("clients", "city")
    op.drop_column("clients", "active")
    op.drop_column("clients", "trade_name")
    op.drop_column("clients", "address")
    op.drop_column("clients", "state")
    op.drop_column("clients", "region")
    op.drop_column("clients", "zip_code")
    op.drop_column("clients", "insc_e")
    op.drop_column("clients", "cnpj")
    op.drop_column("clients", "phone")
    op.alter_column("drivers", "code", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_drivers_code"), table_name="drivers")
    op.add_column("orders", sa.Column("store_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_orders_car_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_by"), table_name="orders")
    op.drop_index(op.f("ix_orders_store_code"), table_name="orders")
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"], unique=False)
    op.drop_constraint(op.f("orders_created_by_fkey"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("orders_car_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(None, "orders", "stores", ["store_id"], ["id"])
    op.drop_column("orders", "car_id")
    op.drop_column("orders", "created_by")
    op.drop_column("orders", "store_code")
    op.add_column(
        "products",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.alter_column("products", "code", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_products_code"), table_name="products")
    op.drop_column("products", "description")
    op.drop_column("products", "value")
    op.alter_column("salesperson", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("salesperson", "image")
    op.drop_column("salesperson", "cpf")
    op.drop_column("salesperson", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesperson",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "salesperson",
        sa.Column("cpf", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "salesperson",
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("salesperson", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "products",
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_products_code"), "products", ["code"], unique=True)
    op.alter_column("products", "code", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("products", "name")
    op.add_column(
        "orders",
        sa.Column("store_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "orders", sa.Column("car_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_car_id_fkey"), "orders", "cars", ["car_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("orders_created_by_fkey"), "orders", "users", ["created_by"], ["id"]
    )
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.create_index(
        op.f("ix_orders_store_code"), "orders", ["store_code"], unique=False
    )
    op.create_index(
        op.f("ix_orders_created_by"), "orders", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_orders_car_id"), "orders", ["car_id"], unique=False)
    op.drop_column("orders", "store_id")
    op.create_index(op.f("ix_drivers_code"), "drivers", ["code"], unique=True)
    op.alter_column("drivers", "code", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "clients", sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "clients", sa.Column("cnpj", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "clients",
        sa.Column("insc_e", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "clients",
        sa.Column("zip_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "clients", sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "clients", sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "clients",
        sa.Column("trade_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "clients",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "clients", sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("contact", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "clients",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_clients_insc_e"), "clients", ["insc_e"], unique=True)
    op.create_index(op.f("ix_clients_cnpj"), "clients", ["cnpj"], unique=True)
    op.drop_index(op.f("ix_stores_code"), table_name="stores")
    op.drop_index(op.f("ix_stores_client_id"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
