"""alter driver profile columns

Revision ID: 9a55009c7d2b
Revises: 8d486df9f056
Create Date: 2026-06-26 16:17:37.211305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a55009c7d2b'
down_revision: Union[str, Sequence[str], None] = '8d486df9f056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('ear', sa.Boolean(), nullable=True))
    op.drop_column('driver_profiles', 'active')
    op.drop_column('driver_profiles', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('driver_profiles', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('driver_profiles', 'ear')
    # ### end Alembic commands ###
