"""db new fields and relationships

Revision ID: be931ceb117a
Revises: 19b202f2f978
Create Date: 2026-08-02 13:50:18.949757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "be931ceb117a"
down_revision: Union[str, Sequence[str], None] = "19b202f2f978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deliveries",
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "deliveries",
        sa.Column("cargo_weight", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "deliveries",
        sa.Column("departed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_deliveries_cargo_weight"), "deliveries", ["cargo_weight"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_invoice_number"),
        "deliveries",
        ["invoice_number"],
        unique=False,
    )
    op.add_column(
        "drivers", sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_index(op.f("ix_drivers_code"), "drivers", ["code"], unique=True)
    op.add_column(
        "order_items",
        sa.Column("item_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "order_items",
        sa.Column("row_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_order_items_row_hash"), "order_items", ["row_hash"], unique=True
    )
    op.add_column(
        "orders",
        sa.Column("branch_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "orders", sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("release_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "orders", sa.Column("released_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("store_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column(
            "operationtype", sa.String(length=10), server_default="sale", nullable=False
        ),
    )
    op.drop_index(op.f("ix_orders_code"), table_name="orders")
    op.create_index(op.f("ix_orders_code"), "orders", ["code"], unique=False)
    op.create_index(
        op.f("ix_orders_branch_code"), "orders", ["branch_code"], unique=False
    )
    op.create_index(
        op.f("ix_orders_store_code"), "orders", ["store_code"], unique=False
    )
    op.create_unique_constraint(
        "uq_orders_branch_code", "orders", ["branch_code", "code"]
    )
    op.drop_column("orders", "type")
    op.add_column(
        "products",
        sa.Column("name_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_products_name_code"), "products", ["name_code"], unique=True
    )
    op.alter_column(
        "stock_movements", "order_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "stock_movements",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_movements",
        "quantity",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_movements", "order_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_index(op.f("ix_products_name_code"), table_name="products")
    op.drop_column("products", "name_code")
    op.add_column(
        "orders",
        sa.Column(
            "type",
            sa.VARCHAR(length=10),
            server_default=sa.text("'out'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_orders_branch_code", "orders", type_="unique")
    op.drop_index(op.f("ix_orders_store_code"), table_name="orders")
    op.drop_index(op.f("ix_orders_branch_code"), table_name="orders")
    op.drop_index(op.f("ix_orders_code"), table_name="orders")
    op.create_index(op.f("ix_orders_code"), "orders", ["code"], unique=True)
    op.drop_column("orders", "operationtype")
    op.drop_column("orders", "store_code")
    op.drop_column("orders", "released_at")
    op.drop_column("orders", "release_reason")
    op.drop_column("orders", "issued_at")
    op.drop_column("orders", "branch_code")
    op.drop_index(op.f("ix_order_items_row_hash"), table_name="order_items")
    op.drop_column("order_items", "row_hash")
    op.drop_column("order_items", "item_number")
    op.drop_index(op.f("ix_drivers_code"), table_name="drivers")
    op.drop_column("drivers", "code")
    op.drop_index(op.f("ix_deliveries_invoice_number"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_cargo_weight"), table_name="deliveries")
    op.drop_column("deliveries", "departed_at")
    op.drop_column("deliveries", "cargo_weight")
    op.drop_column("deliveries", "invoice_number")
    # ### end Alembic commands ###
