"""add column at stock_movement table

Revision ID: c0d6e75dbc64
Revises: 7dc53a99367f
Create Date: 2026-08-24 16:06:56.435213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d6e75dbc64'
down_revision: Union[str, Sequence[str], None] = '7dc53a99367f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_stock_movements_user_id'), 'stock_movements', ['user_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_user_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'user_id')
    # ### end Alembic commands ###
