"""add user at  deliveries table

Revision ID: cd3de0201d89
Revises: 4510705090fd
Create Date: 2026-08-21 11:54:12.331795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3de0201d89'
down_revision: Union[str, Sequence[str], None] = '4510705090fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_deliveries_user_id'), 'deliveries', ['user_id'], unique=False)
    op.create_foreign_key(None, 'deliveries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_index(op.f('ix_deliveries_user_id'), table_name='deliveries')
    op.drop_column('deliveries', 'user_id')
    # ### end Alembic commands ###
