"""add hold fields in orders table

Revision ID: ce1524dbff2f
Revises: 6abf8ba19932
Create Date: 2026-08-20 14:46:13.052010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ce1524dbff2f"
down_revision: Union[str, Sequence[str], None] = "6abf8ba19932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("stock_hold", sa.Boolean(), nullable=False))
    op.add_column(
        "orders",
        sa.Column(
            "stock_hold_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "orders", sa.Column("stock_hold_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_orders_stock_hold"), "orders", ["stock_hold"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_stock_hold"), table_name="orders")
    op.drop_column("orders", "stock_hold_at")
    op.drop_column("orders", "stock_hold_reason")
    op.drop_column("orders", "stock_hold")
    # ### end Alembic commands ###
