"""delete fields at car table

Revision ID: dfe5cd0df175
Revises: ff5c1b638799
Create Date: 2026-08-17 09:18:07.545092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe5cd0df175'
down_revision: Union[str, Sequence[str], None] = 'ff5c1b638799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_capacities', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('cars', 'strength')
    op.drop_column('cars', 'versatility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('versatility', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('strength', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('car_capacities', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
