"""rename order column

Revision ID: e2cef468bf2d
Revises: 98630ddc391a
Create Date: 2026-08-03 14:16:34.571393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cef468bf2d'
down_revision: Union[str, Sequence[str], None] = '98630ddc391a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('operation_type', sa.String(length=10), server_default='sale', nullable=False))
    op.drop_column('orders', 'operationtype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('operationtype', sa.VARCHAR(length=10), server_default=sa.text("'sale'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('orders', 'operation_type')
    # ### end Alembic commands ###
