"""update fields in tables

Revision ID: f07555f99774
Revises: ca6b8a251f7e
Create Date: 2026-04-24 16:18:57.269666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f07555f99774"
down_revision: Union[str, Sequence[str], None] = "ca6b8a251f7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars", sa.Column("plate", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("cars", sa.Column("driver_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_cars_license"), table_name="cars")
    op.create_index(op.f("ix_cars_driver_id"), "cars", ["driver_id"], unique=False)
    op.create_index(op.f("ix_cars_plate"), "cars", ["plate"], unique=True)
    op.create_foreign_key(None, "cars", "drivers", ["driver_id"], ["id"])
    op.drop_column("cars", "license")
    op.add_column(
        "drivers", sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "drivers",
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "drivers",
        sa.Column("type", sa.String(length=50), server_default="B", nullable=False),
    )
    op.add_column("drivers", sa.Column("validity", sa.DateTime(), nullable=True))
    op.add_column(
        "products",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("products", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column(
        "products",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(op.f("ix_products_code"), "products", ["code"], unique=True)
    op.drop_column("products", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_products_code"), table_name="products")
    op.drop_column("products", "image")
    op.drop_column("products", "created_at")
    op.drop_column("products", "active")
    op.drop_column("products", "unit")
    op.drop_column("products", "code")
    op.drop_column("drivers", "validity")
    op.drop_column("drivers", "type")
    op.drop_column("drivers", "license")
    op.drop_column("drivers", "cpf")
    op.add_column(
        "cars", sa.Column("license", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "cars", type_="foreignkey")
    op.drop_index(op.f("ix_cars_plate"), table_name="cars")
    op.drop_index(op.f("ix_cars_driver_id"), table_name="cars")
    op.create_index(op.f("ix_cars_license"), "cars", ["license"], unique=True)
    op.drop_column("cars", "driver_id")
    op.drop_column("cars", "plate")
    # ### end Alembic commands ###
