"""create capacity car table

Revision ID: ff5c1b638799
Revises: 56d1633c31c5
Create Date: 2026-08-17 09:05:33.993160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5c1b638799'
down_revision: Union[str, Sequence[str], None] = '56d1633c31c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_capacities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='m3', nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'unit', name='uq_car_capacity_unit')
    )
    op.create_index(op.f('ix_car_capacities_car_id'), 'car_capacities', ['car_id'], unique=False)
    op.drop_column('cars', 'capacity')
    op.add_column('products', sa.Column('volume_m3_per_unit', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('weight_kg_per_unit', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('boxes_per_pallet', sa.Integer(), nullable=True))
    op.drop_column('products', 'unit_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('products', 'boxes_per_pallet')
    op.drop_column('products', 'weight_kg_per_unit')
    op.drop_column('products', 'volume_m3_per_unit')
    op.add_column('cars', sa.Column('capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_car_capacities_car_id'), table_name='car_capacities')
    op.drop_table('car_capacities')
    # ### end Alembic commands ###
